### ISSUE TITLE
Facilitating integration to snakemake pipeline by removing date appending to results directory

### ISSUE THREAD

**Issue by dilema** [davidemms/OrthoFinder#689]
Hello David !

First, thanks for this awesome tool and for all the efforts you make towards ensuring Orthofinder is easy to use.
I believe one of the typical use case of your tool is to be integrated into a pipeline. As such, one of the most widely used pipeline software in computational biology is [Snakemake](https://snakemake.readthedocs.io/en/stable/). Therefore, I think it's a good idea to facilitate the integration of Orthofinder inside Snakemake.

I tried to write a pull request but I can't wrap my head around all the functions used to create the directory. But let me know if you are interested in the idea but know you wont have time to implement, I can try my best.

### The issue

Orthofinder appends a date to the results directory.
This is not easily manageable inside a Snakemake pipeline (if you never used this tool I can explicit the problem).

### Proposed fixes

1 - When the `-o / --output` option is provided, save the results directly under the specified directory (it was actually the way it worked before [this commit](
https://github.com/davidemms/OrthoFinder/commit/1cf99f44e3848a2b170d718aba7a27241af09718#diff-00a730f2f5e1425c46a4b629f4400a795922f28a63eddc8b1cfe516bd0c8643aR99-R122))
2 - Add a new option to remove the date appending to the results directory

### Current workaround

I'm just adding this to illustrate the problem and offer my current solution if anyone is searching for one.
Let's say in a Snakemake pipeline I want to run Orthofinder and filter the `Orthogroups.tsv` results file.
First I execute Orthofinder with `-o results/orthofinder` and wrap the expected output with the `directory()` function.

```yml
rule run_orthofinder:
    input: 'resources/proteomes'
    output: directory('results/orthofinder')
    shell: 'orthofinder -f {input} -o {output} -X'
```

Then, even if I know where the Orthogroups.tsv file will be, I can't know what will be the date at runtime so I can only use the `results/orthofinder` directory as input:

```yml
rule filter_orthogroups:
    input: 'results/orthofinder',
    output: 'results/filtered_orthgroups.tsv'
    shell: 'python workflow/scripts/filter_orthogroups.py {input} {output}'
```

And get the first subdirectory (you can add regex to be sure it's named `Results_.*`) in the processing script:

```python
 #!/usr/bin/env python3
import os
import sys

def filter_orthogroup(orthogroup):
    # Do something here
    return orthogroup

orthofinderPath = os.path.join('./', sys.argv[1])
outputPath = sys.argv[2]

# To deal with orthofinder creating an output directory with date as name, take the subdir as new input
with os.scandir(orthofinderPath) as dir:
    for entry in dir:
        if entry.is_dir():
            orthofinderPath = entry.path
            break

with open(orthofinderPath, 'r') as input, open(outputPath, 'w') as output:
    for og in input.readLines():
        filtered_og = filter_orthogroup(og)
        output.write(filtered_og)
```

All the best !

**Comment by dilema** [comment]
Well, the `-n` option absolutely does the trick. Sorry for missing it out, but thanks for the help !
For reference, this works as intended and solve my problem:

```yml
name = 'experience'

rule run_orthofinder:
    input: 'resources/proteomes'
    output: directory('results/orthofinder')
    shell: 'orthofinder -f {input} -o {output} -n {name} -X'

rule filter_orthogroups:
    input: 'results/orthofinder/Results_{name}/Orthogroups/Orthogroups.tsv',
    output: 'results/filtered_orthgroups.tsv'
    shell: 'python workflow/scripts/filter_orthogroups.py {input} {output}'
```

Closing the issue then.
