### ISSUE TITLE
conda install failes

### ISSUE THREAD

**Issue by shbrainard** [davidemms/OrthoFinder#881]
Conda install fails on M2 Mac with miniconda installed:

(orthofinder) ➜  ~ conda install -c bioconda orthofinder
Channels:
 - bioconda
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides blast needed by orthofinder-2.3.10-0

Could not solve for environment specs
The following package could not be installed
└─ orthofinder is not installable because it requires
   └─ blast, which does not exist (perhaps a missing channel).

(orthofinder) ➜  ~ conda config --show channels

channels:
  - conda-forge
  - bioconda
  - defaults

**Comment by dimitrademertzi** [comment]
I had the same problem, and it took a while to find a way to resolve this.

After activating the environment, run the following command to change the platform architecture (__osx-64__ instead of __osx-arm64__) for the environment you are using. As far as I understood, it is a compatibility issue of a sort.

`conda activate env`
`conda config --env --set subdir osx-64`

Hope this helps.

**Comment by Brilator** [comment]
Unfortunately, that did not solve it for me. 

```bash
conda install orthofinder
```


```yaml
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides blast needed by orthofinder-2.3.10-0

Could not solve for environment specs
The following packages are incompatible
└─ orthofinder is not installable because there are no viable options
   ├─ orthofinder [2.3.10|2.3.11|...|2.5.5] would require
   │  └─ blast, which does not exist (perhaps a missing channel);
   └─ orthofinder 3.0.1b1 would require
      └─ aster, which does not exist (perhaps a missing channel).
```

```bash
conda config --env --set subdir osx-64
conda install orthofinder
```

```yaml
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed

InvalidSpec: The package "pkgs/main/osx-arm64::_anaconda_depends==2024.02=py311_openblas_1" is not available for the specified platform
```

Can anyone help?
